### ISSUE TITLE
[FEATURE] User can view To-Do list

### ISSUE THREAD

**Issue by dalladirosa** [dalladirosa/todo-app#3]
## Acceptance Criteria

- [x] Fetch data from the API endpoint
- [x] Display the list of tasks retrieved from the API
- [x] Ensure tasks are displayed in the order of their creation date and time (oldest first)
